### PR TITLE
Update draft.md

### PR DESCRIPTION
**Pull request by dA505819**
Added dataset "Aviation Safety" published on kaggle.

### CODE REVIEW

**Comment by jonocarroll** [comment]
Thank you for the submission. Interesting data set. Are you able to include a reference or source for this data?

**Comment by dA505819** [comment]
Ya definitely.
I have taken it from aviation safety network website.  But I think I don't remember the link ):

**Comment by jonocarroll** [comment]
Thank you. Am I mistaken, or is this [the same as the FiveThirtyEight data](https://www.kaggle.com/fivethirtyeight/fivethirtyeight-airline-safety-dataset) from their story https://fivethirtyeight.com/features/should-travelers-avoid-flying-airlines-that-have-had-crashes-in-the-past/ ? They include a [source](https://aviation-safety.net/statistics/). I'm reluctant to include this link as it is not the original dataset.

**Comment by dA505819** [comment]
I didn't know that fivethirtyeight has also done it's research on the data. 
By the way, I downloaded it from official website https://aviation-safety.net/airlinesafety/ and my story link on tableau is as followed: https://public.tableau.com/profile/dhruv.aggarwal8198#!/vizhome/AviationSafety/Story1

**Comment by jonocarroll** [comment]
Added in 41d4de21c29fff06cd261e3722ac8c9b75ae8f81

**Pull request closed without merging**
