### PR TITLE
added Next newsletter

### PR DESCRIPTION
**Pull request by harshvardhaniimi**
Next — Today I Learned About R (https://www.harsh17.in/next)

A short and sweet curated collection of R-related works. Five stories. Four packages. Three jargons. Two tweets. One Meme.

### CODE REVIEW

**Comment by jonmcalder** [comment]
Thanks for the submission @harshvardhaniimi - not sure if you intended to contribute your most recent post from the 10th Nov, but we generally try and stick to content that's been published within the past 2 to 3 weeks, so I've instead added your blog to the list of RSS feeds we track so that future posts can be considered for inclusion going forward.

**Comment by harshvardhaniimi** [comment]
Hi @jonmcalder, thanks for adding my blog’s RSS feed. I actually wanted to add about my weekly newsletter on R (https://www.getrevue.co/profile/harshbutjust). The last edition was published on December 1, 2021 and the next edition will be out coming Wednesday. Is it too late to add it now?

The short url (harsh17.in/next) actually redirects to my Revue profile.

**Comment by jonmcalder** [comment]
@harshvardhaniimi Apologies, somehow I missed your most recent post. But yes, the feed for your Revue profile has been added, so going forward anything you post there each week should automatically pull through as part of the content we review for potential inclusion each week.

If you want something specific to be considered, your PR should link directly to the post itself (e.g. https://www.getrevue.co/profile/harshbutjust/issues/what-happened-in-last-two-months-next-issue-9-897446)

**Comment by harshvardhaniimi** [comment]
That's amazing — so I will not have to put in the links directly, but it'd pull from Revue automatically? I'm unaware of how this works. We can technically use RSS feeds with websites, but what goes on in the background for newsletters like Revue?

**Pull request closed without merging**
