### PR TITLE
add interaction-measurement error blog post

### PR DESCRIPTION
**Pull request by malcolmbarrett**

### CODE REVIEW

**Comment by maelle** [comment]
Thanks!

**Comment by maelle** [comment]
Next time put it at the bottom of the list, I think we tend to add them chronologically 😉

**Comment by maelle** [comment]
Cf #367

**Comment by malcolmbarrett** [comment]
Oh, ok. Will do! I'm just doing my part to improve the documentation :stuck_out_tongue_winking_eye:

**Pull request merged**
