### PR TITLE
Adding a new package

### PR DESCRIPTION
**Pull request by monty-se**
Hi rweekly team,

I have just added a new package to your weekly newsletter.

Thank you
Montasser

### CODE REVIEW

**Comment by BatoolMM** [comment]
Very interesting package, thank you, Montasser.
BTW, I love `load_pinstimation_for_good()`

**Review by BatoolMM — APPROVED** [review]

**Comment by monty-se** [comment]
Thanks @BatoolMM 
I have just discussed with my co-author, and, if possible, we would like to change the text describing the package to:

PINstimation: A package for the estimation of models of probability of informed trading

Would it work? Shall I make another pull request with the updated text? Thanks. 

PS: Thinking of changing it to ’load_pinstimation_for_ever()’ :)

**Comment by BatoolMM** [comment]
No need for another PR, I just changed the wording! 

Let me know if I missed anything!

**Comment by monty-se** [comment]
It is great! Thanks for adding the package to rweekly newsletter!

**Pull request merged**
