### PR TITLE
Adding blogpost (not sure if "tutorial" is the right place since there is not a lot of R code)

### PR DESCRIPTION
**Pull request by sinarueeger**

### CODE REVIEW

**Comment by maelle** [comment]
Maybe rather insights?

**Comment by sinarueeger** [comment]
Insights sounds good (I was hesitating between tutorial and insights).

**Comment by maelle** [comment]
Ok, I'll let you update the PR. :-)

**Comment by sinarueeger** [comment]
Ok, let me try - still very much a beginner with these PRs. Let me know if I need to redo it.

**Review by sinarueeger — COMMENTED** [review]
Moved blogpost from `tutorials` to `insights`

**Comment by maelle** [comment]
Thanks!

**Pull request merged**
