### PR TITLE
Release: 2018-8

### PR DESCRIPTION
**Pull request by qinwf**
I will not have a laptop with me tomorrow and created this PR first.

### CODE REVIEW

**Comment by jonmcalder** [comment]
Ok cool. Thanks @qwinf!

**Comment by rpodcast** [comment]
@qinwf did you want one of us to help merge?  Happy to assist in any way I can

**Comment by qinwf** [comment]
Yes, @thercast Thanks! Next time feel free to merge it.

**Comment by jonmcalder** [comment]
Apologies - I meant to merge this but forgot to set a reminder for myself 🙈

**Pull request merged**
