### PR TITLE
Updated draft.md

### PR DESCRIPTION
**Pull request by DougVegas**
Added:

- link to Remix Institute's latest data science strategy blog on saying no to useless, non-value added work

### CODE REVIEW

**Comment by jonocarroll** [comment]
Thank you for the submission, but I don't see the R angle in this piece. The article itself is interesting but we focus on R-related links.

**Comment by DougVegas** [comment]
Hello, @jonocarroll 

Per your <a href="https://github.com/rweekly/rweekly.org/blob/gh-pages/CONTRIBUTING.md" target = "_blank">Contributing Guide</a>, I submitted this link under the "Insights" section. Here is what the Contributing Guide says about the Insights section:

<b>Articles that talks about R and data science in general (usually no code embedded).</b>

There is no code embedded in the article I submitted, and it was about data science in general. Additionally, the R package <code>RemixAutoML</code> is mentioned in the article. 

Would you please reconsider the submission as it is in line with R-Weekly's Contributing Guide? I'd appreciate your review. Thank you and have a good week.

**Comment by jonocarroll** [comment]
This is perhaps a matter of interpretation - we typically interpret this as

"Articles which cover 'R *and* data science in general'" (this being one topic, the interactions between R and data science)

rather than

"Articles which cover either R or data science in general" (either topic).

The mention in passing of one R package does not meet our criteria for inclusion. I have discussed this with the editors team. We thank you for your submission though and encourage you to submit R-related links in the future.

**Comment by DougVegas** [comment]
Thank you for reconsidering and will do for next time.

**Pull request closed without merging**
