### PR TITLE
Add about us to about page

### PR DESCRIPTION
**Pull request by qinwf**
#132

### CODE REVIEW

**Review by maelle — COMMENTED** [review]
Looks good, thanks a lot!

Welcome -> welcoming

And you do not want to write your name and that you are the founder? As you wish!

**Comment by qinwf** [comment]
Thanks. 

Hao Zhu, Kun Ren and me are both founders. Maybe the list is a bit long. 

LOL.

**Comment by maelle** [comment]
you should definitely add that list!

**Comment by qinwf** [comment]
I think we can add a contact email to the end of the list, so people know how to reach us with email. 

eg, mail@rweekly.org

If we add multiple founders' name, people might be confused about who to contact.

**Comment by maelle** [comment]
I don't think so? I feel you 3 should be honoured somehow 😉

**Comment by maelle** [comment]
But great idea to add a contact address

**Pull request merged**
