### PR TITLE
Update draft.md

### PR DESCRIPTION
**Pull request by maelle**
Adds an interesting blog post building on mine that had been added previously (thanks by the way!)

### CODE REVIEW

**Review by jonmcalder — COMMENTED** [review]
We generally "freeze" the draft on Sunday evening given that RWeekly is released each Monday. Maybe it's better to include this follow-up in next weeks edition? 😸

**Comment by maelle** [comment]
Yeah I've just read that in the wiki 🙈

**Comment by qinwf** [comment]
Added in https://github.com/rweekly/rweekly.org/commit/61a79f782e67aea6a7d1b8dc6a94bcbb8c7fe8c8

**Comment by maelle** [comment]
thank you!

**Pull request closed without merging**
