### PR TITLE
big heatmap from big matrices

### PR DESCRIPTION
**Pull request by gdevailly**
Addition of the same blog post in both English and French.
Not really sure if it should go in tutorial or insight. I put it on insight.

### CODE REVIEW

**Comment by tonyelhabr** [comment]
Thanks! I think I will end up putting this in Resources. It doesn't quite fall under the tutorials umbrella (which is intended for posts demonstrating specific packages/tools), and not quite under Insights or Academia.

**Comment by gdevailly** [comment]
Unless I am mistaken, the current R weekly issue (https://rweekly.org/2020-26.html) only mentioned the French version of the blogpost, and not the English one available here https://gdevailly.netlify.app/post/plotting-big-matrices-in-r/

Is it possible to share the English version of this blogpost through R weekly too?

**Comment by tonyelhabr** [comment]
I didn't forget about it! I just thought it would stand out more with just the French version. But since you are explicitly requesting it and I don't see any harm in it, I've added it.

**Comment by gdevailly** [comment]
Thanks!

**Pull request merged**
