### PR TITLE
Add presentation on chopping dates with santoku

### PR DESCRIPTION
**Pull request by hughjonesd**

### CODE REVIEW

**Comment by Ryo-N7** [comment]
thank you!

**Comment by hughjonesd** [comment]
Actually, sorry guys, but could you possibly revert this PR? While I'm sympathetic to many of the protests in the US, I don't support the idea of renaming the Ronald Fisher lectures. I think this is a mistaken idea, and I would feel bad about having my work associated with it. I probably should have worked this out in time for last week! I greatly appreciate your work on rweekly.org, and respect your differing views on this issue.

**Comment by qinwf** [comment]
I did not understand [rweekly/rweekly.org/pull/727#issuecomment-643174275](https://github.com/rweekly/rweekly.org/pull/727#issuecomment-643174275). 

But I think you want to revert this PR.

I updated in https://github.com/rweekly/rweekly.org/commit/7b88fd1b486563dd9a3adcd6fb6168bedd171a88 .

**Comment by hughjonesd** [comment]
Thank you!

>

**Pull request merged**
