### PR TITLE
new CRAN package: ggplotify 

### PR DESCRIPTION
**Pull request by GuangchuangYu**
see <https://cran.r-project.org/package=ggplotify>.

### CODE REVIEW

**Comment by qinwf** [comment]
Thanks!

**Comment by pigian** [comment]
see https://cran.r-project.org/web/packages/hmix/index.html

**Comment by jonocarroll** [comment]
@pigian is this a new submission to RWeekly? If so, it should be in a new pull request of its own.

**Comment by pigian** [comment]
Yes, sorry, I will make a new pull, thx.

GV

Il Mer 25 Set 2024, 00:48 Jonathan Carroll ***@***.***> ha
scritto:

**Pull request merged**
