### PR TITLE
Update draft md

### PR DESCRIPTION
**Pull request by kbodwin**

### CODE REVIEW

**Comment by qinwf** [comment]
It is a really good release. I am enjoying reading it

**Comment by qinwf** [comment]
You can merge PR yourself, and commit to the gh-pages branch to release the new post.

**Comment by rpodcast** [comment]
Hi @qinwf , I don't believe @kbodwin  has the necessary permissions to merge in the PRs.  I did a quick scan of the teams associated with the repo and didn't see her name in the members list.  I don't think I have the permissions to add her myself so if you could check on this that would be great!

**Comment by qinwf** [comment]
@rpodcast Thank you for the update. I sent her a new GitHub invitation, the previous one was outdated.

**Pull request merged**
