### PR TITLE
Adding fabricerin and bubblyr package

### PR DESCRIPTION
**Pull request by feddelegrand7**
Hi rweekly team, 

I've added the {fabricerin} package to the **Github packages section** and the {bubblyr} package to the **CRAN updates** section. 

Cheers !

### CODE REVIEW

**Comment by jonocarroll** [comment]
Did you mean to close this? I'm happy to merge it.

**Comment by feddelegrand7** [comment]
Hi jon, 

Thank you very much but I think I've used an old draft file because I'm not seeing the last commits on it. Could you confirm please, if it's OK I'll reopen the PR. 

Thanks again.

**Comment by jonocarroll** [comment]
I believe GH will do the rebase onto current master draft.md when we merge, so I'll reopen, merge, and confirm.

**Comment by feddelegrand7** [comment]
Ah I understand, thank you very much Jon :)

**Comment by jonocarroll** [comment]
Reopening showed the merge conflicts, which I've resolved with the nice new merging options.

**Comment by feddelegrand7** [comment]
Yes, I saw some conflicts earlier that's way I closed the PR, thank you for fixing the issues

**Pull request merged**
