### PR TITLE
RECON contribtions

### PR DESCRIPTION
**Pull request by thibautjombart**
Includes:

- new package `reportfactory`

- R tips podcast series

### CODE REVIEW

**Comment by maelle** [comment]
Yay, thanks!

**Comment by dirkschumacher** [comment]
Isn't that still the old draf?

**Comment by maelle** [comment]
Oops cc @qinwf

**Comment by qinwf-nuan** [comment]
Thanks, updated.

**Comment by qinwf** [comment]
Thanks, updated.

**Pull request merged**
