### PR TITLE
Added new article under R in real world

### PR DESCRIPTION
**Pull request by amrrs**

### CODE REVIEW

**Comment by maelle** [comment]
Thanks! Isn't it more a tutorial?

**Comment by amrrs** [comment]
It didn't read like a tutorial hence submitted in this section

**Comment by amrrs** [comment]
Should i close this and submit under Tutorials? @maelle

**Comment by maelle** [comment]
you can change this PR I think?

**Comment by amrrs** [comment]
now it has conflicts ☹️

**Pull request closed without merging**
