### PR TITLE
Add a new pkg and blog post

### PR DESCRIPTION
**Pull request by privefl**

### CODE REVIEW

**Comment by suzanbaert** [comment]
Hi Florian. Thanks for submitting. 
Just one remark on the blog post. Could you move it to the tutorial section? As you can see in the [contribution guide](https://github.com/rweekly/rweekly.org/blob/gh-pages/CONTRIBUTING.md) insights posts are typically about data sicence and R in general. Your post would be better categorized as Tutorial. Thanks!

**Comment by privefl** [comment]
Sorry, I thought talking about data frames in general was more an insight than a tutorial.
Tell me if you really want me to move it.

**Comment by privefl** [comment]
I've moved my blog post in Tutorials.

**Comment by suzanbaert** [comment]
Thank you!

**Pull request merged**
