### PR TITLE
Update draft.md

### PR DESCRIPTION
**Pull request by statnmap**
Add some blog posts we forgot to propose to Rweekly last week, a new blog post and a video (in French).

### CODE REVIEW

**Comment by RobWHickman** [comment]
the Rweekly edition for this has been published but I added it to the international section of the current draft

**Comment by statnmap** [comment]
Hi, 
I do not understand why you put the article on "twitter analysis" in R Internationally as it is a series of 3  articles written English.  
And the three other resources, which those are in French, are not listed in the current draft.

**Comment by RobWHickman** [comment]
Hi Sébastien, my bad, I'll update it in the latest draft. As for the organisation of the draft, I throw things in roughly as I find them during the week so it'll be moved to its correct place by release :)

**Comment by statnmap** [comment]
Thanks. No worries !

**Pull request closed without merging**
