### PR TITLE
added blog post again

### PR DESCRIPTION
**Pull request by MCMaurer**
# Adding new content to R Weekly issue

I am adding a post from my personal blog on creating plots using custom `ggplot2` themes and the `ggtext` and `ggh4x` packages.

I submitted another PR for this last week, but it was closed and not added to the draft, despite the editor saying it was added. Hope this is ok!

## Type of Content

**Please select to which section(s) your post belongs!**

 

- [x] Tutorials - R tutorials for how to use certain packages and tools (usually code is embedded)
- [ ] Insights - Articles that talk about R and data science in general (usually no code embedded)
- [ ] R in Real World - Posts that discuss analyses that use R to analyze real-world data sets
- [ ] R in Organization - R use cases/events that showcase how organizations are utilizing or integrating R
- [ ] R in Academia - R use cases that showcase how Academia is utilizing R
- [ ] International - Non-English R related content
- [ ] Videos and Podcasts - Videos and Podcasts about R
- [ ] Resources - long posts, websites, books, slides, list, cheat sheets, or other learning resources in general that are more officially aggregated as a guide material
- [ ] Jobs - R Jobs
- [ ] New Packages and Tools - New packages and tools that have been created or published in the past two weeks.
- [ ] Updated Packages - New releases of tools and packages for R
- [ ] Call for Participation - New R groups, communities or competitions here. 
- [ ] Upcoming Events - Interesting R-related events or call for Participation section.

### I'd like to propose an Image from my new content!

 

Please feel free to suggest an image from your content to be added in the next issue. Any image added has to be re-sized to a max width 600px. This can be carried out using [rweekly.tools](https://github.com/rweekly/rweekly.tools) or any online tool.

- [ ] Yes, I proposed an image and resized it
- [ ] Yes, I proposed an image but didn't resized it
- [x] No, I didn't propose an image

# Checklist:

- [x] My content is R-related 
- [x] All images suggested are re-sized before has been added to the PR
- [x] I've submitted my content between Monday-Friday to allow for it to be voted by R Weekly editors for highlights

### CODE REVIEW

**Comment by MCMaurer** [comment]
Oh my gosh I am so sorry, I think I accidentally merged this PR while trying to open it. I'm honestly not sure how that happened, I didn't figure I would have privileges to do that. In the interest of not messing things up further and leaving a mysterious commit history, I will wait til an admin can take a look.

Again, sincere apologies!

**Comment by jonocarroll** [comment]
This is odd, but I think it's because you made edits that brought the your fork back in line with our repo, which required 0 changes (and so 0 commits were added to the history)

> [MCMaurer](https://github.com/MCMaurer) merged 0 commits into [rweekly:gh-pages](https://github.com/rweekly/rweekly.org) from [MCMaurer:gh-pages](https://github.com/MCMaurer/rweekly.org) 2 hours ago

but I don't see the entry in any posts. I'll try to track down what happened and make sure it's in the next issue.

**Comment by jonocarroll** [comment]
Added manually in https://github.com/rweekly/rweekly.org/commit/30ab0e96c2f9e68d512ccc07154c68ef33aded83

**Comment by MCMaurer** [comment]
@jonocarroll ahhh yeah that totally makes sense. That's what I get for taking the lazy route when GitHub suggested bringing my fork up to date. In the future, if I have multiple submissions, I'll just make separate forks for them to keep things tidy. Thanks for getting both those posts added, I appreciate it!

**Pull request merged**
