### PR TITLE
Cranberries script update

### PR DESCRIPTION
**Pull request by rpodcast**
I probably spent a bit too much time on this, but it was a fun technical challenge to see if we could bring some more automation and less manual copy-pasting to the cranberries function.  In this PR I leveraged a few packages to import the cranberries RSS feeds directly into a tidy format, and use some tidyverse logic combined with the awesome `pkgsearch` package to obtain metadata in a clean way.  I'm aware of the merge conflicts and will be happy to clean up if others like the approach.  To use the updated script, make sure the following packages are installed:

* `tidyRSS`
* `pkgsearch`
* `dplyr`
* `lubridate`

@jonocarroll & @qinwf  would you mind giving it a quick look?

### CODE REVIEW

**Review by qinwf — APPROVED** [review]
LGTM

**Comment by qinwf** [comment]
I will use this script in the https://space.rweekly.org home page. 

Add two new generated sections for new packages and updated packages.

**Comment by maelle** [comment]
So do we really want to add all updates and new packages? I think it's better to only highlight a few, especially those with release notes that are submitted to us in the form of a blog post or so. That's what I've been doing. :innocent:

**Comment by jonocarroll** [comment]
My intention was that this would scrape all of them, then an editor would
have everything to choose from, but I never intended that all of them would
be included.

**Comment by tonyelhabr** [comment]
When I used the Rweekly Space a couple of weeks ago, I used it like @jonocarroll suggested:--looked at all of the links and narrowed it down to ones that seemed most relevant to a broad audience. It was certainly convenient to have all of the links already in one place.

**Comment by maelle** [comment]
Cool, thanks both, this makes me feel better, that's how I used the links from the space.

**Review by jonocarroll — APPROVED** [review]

**Pull request merged**
