### PR TITLE
Added blog post about Factfulness

### PR DESCRIPTION
**Pull request by mhoehle**
If you want to have a picture spoiler, one could link to http://staff.math.su.se/hoehle/blog/figure/source/2018-07-02-factfulness/ARTISTICMOUNTAINPLOT-1.png. I proposed this in the PR, but you might want to remove the  if that's not wanted.

### CODE REVIEW

**Comment by maelle** [comment]
Good idea to add the picture, thanks for the PR. If your blog has an RSS feed, you could also submit it directly to https://rweekly.org/submit in order not to have to do one PR for each post (and all your posts are about R anyway).

**Comment by maelle** [comment]
(the submit link is broken at the moment though)

**Comment by mhoehle** [comment]
Thanks! I think I have submitted the RSS feed already, but apparently the service is not working atm? At least my last post was automatically (?) added to the rweekly.org draft page. Or somebody did it manually?

**Comment by maelle** [comment]
yes there were some server issues recently cc @qinwf

**Comment by mhoehle** [comment]
Thx!

**Comment by qinwf** [comment]
The submit page is back. Thanks for the notice.

**Pull request merged**
