### PR TITLE
Add SARS-CoV-2 shiny app

### PR DESCRIPTION
**Pull request by SineadMorris**
Hi, I've added a link to a new shiny app simulating the effects of different SARS-CoV-2 vaccine rollout strategies. 

This is my first time contributing to rweekly so apologies if I've made any mistakes creating the request!

### CODE REVIEW

**Comment by iamericfletcher** [comment]
Link for those who are curious:

[https://grenfelllab.shinyapps.io/sarscov2vaccine/](https://grenfelllab.shinyapps.io/sarscov2vaccine/)

Awesome stuff @SineadMorris!

**Comment by MilesMcBain** [comment]
Thank you for the contribution! 

I am hesitant to merge just now, since I cannot find a link to the R source for this app. Is one available?

**Comment by tonyelhabr** [comment]
@iamericfletcher For Shiny apps that we include in the weekly newsletter we prefer to have the source available. Can you point out where the source is?

**Comment by iamericfletcher** [comment]
@tonyelhabr - I don't have a link to the source. I was just trying to help OP out by adding a link so people can access it more easily from within the PR.

**Comment by tonyelhabr** [comment]
I went ahead and added the Shiny app to this week's newsletter. As I mentioned before, we prefer to have the code available for the app, but it's not a strict rule.

**Pull request closed without merging**
